/**
 * Hand-maintained types matching apps/api's NestJS DTOs.
 *
 * These were briefly advertised as generated by `pnpm generate:web-types`
 * (scripts/generate-web-types.ts), but that script was never written and the
 * remaining work to create it is disproportionate to the value it would bring
 * for a single-frontend project. This file is therefore maintained by hand.
 *
 * If a second frontend or public API consumer appears, invest in a proper
 * openapi-generator pipeline at that point — not before.
 */

export type SessionRole = 'ADMIN' | 'ISSUER' | 'UNAPPROVED'

export interface SessionResponse {
  address: string | null
  role: SessionRole | null
}

export interface NonceResponse {
  nonce: string
}

export interface VerifyRequest {
  message: string
  signature: string
}

export interface VerifyResponse {
  address: string
  role: SessionRole
  requestStatus?: string
}

export interface LogoutResponse {
  success: boolean
}

export type AccessRequestStatus = 'PENDING' | 'APPROVED' | 'REJECTED'

export interface AccessRequestRow {
  id: string
  walletAddress: string
  name: string | null
  email: string | null
  organization: string | null
  website: string | null
  description: string | null
  createdAt: string
  status: AccessRequestStatus
  decidedAt: string | null
  rejectionReason: string | null
}

export interface AdminRequestsResponse {
  requests: AccessRequestRow[]
}

export interface ApproveUserRequest {
  walletAddress: string
  txHash: string
}

export interface RejectUserRequest {
  walletAddress: string
  reason?: string
}

export interface IssuerRequestStatusResponse {
  requestStatus: 'NONE' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED'
}

export interface IssuerStatsResponse {
  totalIssued: number
  recentActivityCount: number
}

export interface IssuerDocumentRow {
  docHash: string
  documentType?: string
  recipientName?: string
  recipientEmail?: string
  txHash: string
  cid?: string | null
  metadataCid?: string | null
  anchoredAt: string
  batchId: string | null
}

export interface IssuerDocumentsResponse {
  documents: IssuerDocumentRow[]
  nextCursor: string | null
}

export interface IssuerDocumentsQuery {
  search?: string
  cursor?: string
}

export interface IssuerActivityEntry {
  action: string
  detail?: string
  createdAt: string
  txHash?: string
  docHash?: string
}

export interface IssuerActivityQuery {
  action?: string
  cursor?: string
}

export interface RetryPinResponse {
  success: boolean
  metadataCid: string | null
  message: string
}

export interface IssuerActivityResponse {
  entries: IssuerActivityEntry[]
  nextCursor: string | null
}

export interface IssuerAccessRequestBody {
  name?: string
  email?: string
  organization?: string
  website?: string
  description?: string
}

export interface AnchorDocumentRequest {
  documentHash: string
  /** Hash of the confirmed `anchorDocument` tx, signed by the issuer's own wallet. */
  txHash: string
  documentType: string
  recipientEmail?: string
  recipientName?: string
  /** IPFS CID of the PDF, when the issuer chose to store a copy. */
  cid?: string
}

export interface AnchorDocumentResponse {
  success: boolean
  txHash: string
  documentHash: string
  cid: string | null
  metadataCid: string | null
  timestamp: string
  status: string
  message: string
}

export interface BatchAnchorDocumentEntry {
  documentHash: string
  recipientEmail: string
  recipientName: string
  /** IPFS CID of the PDF, when storage was requested. */
  cid?: string
}

export interface BatchAnchorRequest {
  documents: BatchAnchorDocumentEntry[]
  documentType: string
  /** Hash of the confirmed `anchorMerkleBatch` tx, signed by the issuer's own wallet. */
  txHash: string
  batchId: string
}

export interface BatchAnchorResponse {
  success: boolean
  batchId: string
  merkleRoot: string
  txHash: string
  documentCount: number
  timestamp: string
  status: string
  message: string
}

export interface VerifyDocumentRequest {
  documentHash: string
  pdfContent?: string
}

export interface VerifyOnchainData {
  transactionHash: string
  blockNumber: number
  network: string
}

export interface VerifyDocumentResponse {
  success: boolean
  isValid: boolean
  documentHash?: string
  issuer?: string
  documentType?: string
  issuedDate?: string
  status?: 'active' | 'not_found'
  message: string
  onchainData?: VerifyOnchainData
  cid?: string | null
  gatewayUrl?: string | null
  error?: string
}

export interface PdfUploadResponse {
  success: boolean
  filename: string
  fileSize: number
  documentHash: string
  /** IPFS CID, or null when storage was not requested or the pin failed. */
  cid: string | null
  gatewayUrl: string | null
  pinned: boolean
  /** Present only when pinning failed. The document is still valid. */
  pinError?: string
  timestamp: string
  message: string
}

export interface IpfsPinStatusResponse {
  cid: string
  pinned: boolean
  gatewayUrl: string
}

export interface IpfsHealthResponse {
  provider: string
  configured: boolean
  gateway: string
}

export interface PdfHashRequest {
  pdfContent: string
  filename: string
}

export interface ApiErrorBody {
  error?: string
  message?: string | string[]
}

// --- Admin API types ---

export interface AdminStatsResponse {
  totalIssuers: number
  pendingApprovals: number
  documentsAnchored: number
  suspendedIssuers: number
}

export type IssuerStatus = 'ACTIVE' | 'SUSPENDED'

export interface IssuerRow {
  walletAddress: string
  organization: string | null
  name: string | null
  email: string | null
  website: string | null
  metadataUri: string | null
  status: IssuerStatus
  documentCount: number
  registeredAt: string
  registerTxHash: string
  suspendedAt: string | null
  suspendTxHash: string | null
}

export interface IssuerListResponse {
  issuers: IssuerRow[]
  nextCursor: string | null
}

export interface IssuerDetailResponse {
  issuer: IssuerRow
  recentActivity: Array<{
    action: string
    detail: string | null
    createdAt: string
    txHash: string | null
  }>
}

export interface SuspendIssuerRequest {
  walletAddress: string
  txHash: string
}

export interface ReactivateIssuerRequest {
  walletAddress: string
  txHash: string
}

export interface UploadIssuerMetadataResponse {
  metadataUri: string
  cid: string
}

export interface SetIssuerMetadataRequest {
  txHash: string
}

export interface SetIssuerMetadataResponse {
  issuer: IssuerRow
}

export interface AdminDocumentRow {
  docHash: string
  issuerAddress: string
  issuerName: string | null
  documentType: string | null
  recipientName: string | null
  recipientEmail: string | null
  cid: string | null
  txHash: string
  anchoredAt: string
  batchId: string | null
}

export interface AdminDocumentsResponse {
  documents: AdminDocumentRow[]
  nextCursor: string | null
}

export interface AuditLogEntry {
  id: string
  action: string
  actorAddress: string
  actorName: string
  targetRef: string
  txHash: string | null
  detail: string | null
  createdAt: string
}

export interface AuditLogResponse {
  entries: AuditLogEntry[]
  nextCursor: string | null
}

export interface PlatformStatsResponse {
  totalDocumentsAnchored: number
  totalVerifications: number
}
