/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DocumentAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ROLE"
      | "anchorDocument"
      | "anchorMerkleBatch"
      | "documents"
      | "getDocument"
      | "getMerkleBatch"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isIssuerApproved"
      | "merkleBatches"
      | "renounceRole"
      | "revokeDocument"
      | "revokeRole"
      | "revokedDocuments"
      | "supportsInterface"
      | "usedMerkleRoots"
      | "verifyDocument"
      | "verifyMerkleProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentAnchored"
      | "DocumentRevoked"
      | "MerkleRootAnchored"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchorDocument",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorMerkleBatch",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "documents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuerApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleBatches",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedDocuments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedMerkleRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMerkleProof",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorMerkleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "documents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isIssuerApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokedDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedMerkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMerkleProof",
    data: BytesLike
  ): Result;
}

export namespace DocumentAnchoredEvent {
  export type InputTuple = [
    documentHash: BytesLike,
    issuer: AddressLike,
    documentType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentHash: string,
    issuer: string,
    documentType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentHash: string;
    issuer: string;
    documentType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentRevokedEvent {
  export type InputTuple = [
    documentHash: BytesLike,
    issuer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentHash: string,
    issuer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentHash: string;
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootAnchoredEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    issuer: AddressLike,
    documentCount: BigNumberish,
    timestamp: BigNumberish,
    batchId: string
  ];
  export type OutputTuple = [
    merkleRoot: string,
    issuer: string,
    documentCount: bigint,
    timestamp: bigint,
    batchId: string
  ];
  export interface OutputObject {
    merkleRoot: string;
    issuer: string;
    documentCount: bigint;
    timestamp: bigint;
    batchId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentAnchor;
  waitForDeployment(): Promise<this>;

  interface: DocumentAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ROLE: TypedContractMethod<[], [string], "view">;

  anchorDocument: TypedContractMethod<
    [_documentHash: BytesLike, _documentType: string],
    [void],
    "nonpayable"
  >;

  anchorMerkleBatch: TypedContractMethod<
    [_merkleRoot: BytesLike, _documentCount: BigNumberish, _batchId: string],
    [void],
    "nonpayable"
  >;

  documents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        hash: string;
        issuer: string;
        timestamp: bigint;
        revoked: boolean;
        documentType: string;
      }
    ],
    "view"
  >;

  getDocument: TypedContractMethod<
    [_documentHash: BytesLike],
    [
      [string, bigint, boolean, string] & {
        issuer: string;
        timestamp: bigint;
        revoked: boolean;
        documentType: string;
      }
    ],
    "view"
  >;

  getMerkleBatch: TypedContractMethod<
    [_merkleRoot: BytesLike],
    [
      [string, bigint, bigint, string] & {
        issuer: string;
        documentCount: bigint;
        timestamp: bigint;
        batchId: string;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isIssuerApproved: TypedContractMethod<
    [_issuer: AddressLike],
    [boolean],
    "view"
  >;

  merkleBatches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        merkleRoot: string;
        issuer: string;
        documentCount: bigint;
        timestamp: bigint;
        batchId: string;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeDocument: TypedContractMethod<
    [_documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokedDocuments: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  usedMerkleRoots: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyDocument: TypedContractMethod<
    [_documentHash: BytesLike],
    [boolean],
    "view"
  >;

  verifyMerkleProof: TypedContractMethod<
    [_proof: BytesLike[], _merkleRoot: BytesLike, _leaf: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchorDocument"
  ): TypedContractMethod<
    [_documentHash: BytesLike, _documentType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorMerkleBatch"
  ): TypedContractMethod<
    [_merkleRoot: BytesLike, _documentCount: BigNumberish, _batchId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "documents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        hash: string;
        issuer: string;
        timestamp: bigint;
        revoked: boolean;
        documentType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [_documentHash: BytesLike],
    [
      [string, bigint, boolean, string] & {
        issuer: string;
        timestamp: bigint;
        revoked: boolean;
        documentType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMerkleBatch"
  ): TypedContractMethod<
    [_merkleRoot: BytesLike],
    [
      [string, bigint, bigint, string] & {
        issuer: string;
        documentCount: bigint;
        timestamp: bigint;
        batchId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isIssuerApproved"
  ): TypedContractMethod<[_issuer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleBatches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        merkleRoot: string;
        issuer: string;
        documentCount: bigint;
        timestamp: bigint;
        batchId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDocument"
  ): TypedContractMethod<[_documentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokedDocuments"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedMerkleRoots"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<[_documentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyMerkleProof"
  ): TypedContractMethod<
    [_proof: BytesLike[], _merkleRoot: BytesLike, _leaf: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DocumentAnchored"
  ): TypedContractEvent<
    DocumentAnchoredEvent.InputTuple,
    DocumentAnchoredEvent.OutputTuple,
    DocumentAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentRevoked"
  ): TypedContractEvent<
    DocumentRevokedEvent.InputTuple,
    DocumentRevokedEvent.OutputTuple,
    DocumentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootAnchored"
  ): TypedContractEvent<
    MerkleRootAnchoredEvent.InputTuple,
    MerkleRootAnchoredEvent.OutputTuple,
    MerkleRootAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DocumentAnchored(bytes32,address,string,uint256)": TypedContractEvent<
      DocumentAnchoredEvent.InputTuple,
      DocumentAnchoredEvent.OutputTuple,
      DocumentAnchoredEvent.OutputObject
    >;
    DocumentAnchored: TypedContractEvent<
      DocumentAnchoredEvent.InputTuple,
      DocumentAnchoredEvent.OutputTuple,
      DocumentAnchoredEvent.OutputObject
    >;

    "DocumentRevoked(bytes32,address,uint256)": TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;
    DocumentRevoked: TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;

    "MerkleRootAnchored(bytes32,address,uint256,uint256,string)": TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;
    MerkleRootAnchored: TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
